# Generated by Django 2.2.8 on 2020-06-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField()),
                ('text', models.CharField(max_length=350)),
            ],
        ),
    ]
